# Generated by Django 5.0.2 on 2024-04-03 10:35

from django.db import migrations
import openpyxl
from django.core.exceptions import ValidationError

def insert_kenyan_banks(apps, schema_editor):
    Bank = apps.get_model('mashinani', 'Bank')
    
    try:
        # Load data from Excel workbook
        wb = openpyxl.load_workbook('mashinani/data/data.xlsx')
        sheet = wb['Bank']
        
        # Extract bank names from the Excel sheet
        banks_data = []
        for row in sheet.iter_rows(min_row=2, values_only=True):  # Assuming data starts from second row
            bank_name = row[0]  # Assuming bank name is in the first column
            banks_data.append({'bank_name': bank_name})
        
        # Insert data into the model
        for data in banks_data:
            try:
                Bank.objects.create(**data)
            except ValidationError as e:
                print(f"Validation Error: {e}")
    except FileNotFoundError:
        print("File not found. Please check the path to the Excel file.")
    except Exception as e:
        print(f"An error occurred: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('mashinani', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_kenyan_banks)
    ]
