# Generated by Django 5.0.2 on 2024-04-03 10:38

from django.db import migrations

import openpyxl
from django.core.exceptions import ValidationError

def insert_kenyan_institutions(apps, schema_editor):
    Institution = apps.get_model('mashinani', 'Institution')
    
    try:
        # Load data from Excel workbook
        wb = openpyxl.load_workbook('mashinani/data/data.xlsx')
        sheet = wb['Institution']
        
        # Extract institution names from the Excel sheet
        institutions_data = []
        for row in sheet.iter_rows(min_row=2, values_only=True):  # Assuming data starts from second row
            institution_name = row[0]  # Assuming institution name is in the first column
            institutions_data.append({'institution_name': institution_name})
        
        # Insert data into the model
        for data in institutions_data:
            try:
                Institution.objects.create(**data)
            except ValidationError as e:
                print(f"Validation Error: {e}")
    except FileNotFoundError:
        print("File not found. Please check the path to the Excel file.")
    except Exception as e:
        print(f"An error occurred: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('mashinani', '0002_auto_20240403_1335'),
    ]

    operations = [
        migrations.RunPython(insert_kenyan_institutions)
    ]
