# Generated by Django 5.0.2 on 2024-04-03 11:37

from django.db import migrations
import openpyxl
from django.core.exceptions import ObjectDoesNotExist

def insert_regions(apps, schema_editor):
    Region = apps.get_model('mashinani', 'Region')
    Country = apps.get_model('mashinani', 'Country')

    try:
        # Load data from Excel workbook
        wb = openpyxl.load_workbook('mashinani/data/data.xlsx')
        sheet = wb['Region']

        # Iterate over rows in the Excel sheet and extract region information
        regions_data = []
        for row in sheet.iter_rows(min_row=2, values_only=True):  # Assuming data starts from second row
            country_name = row[0]  # Assuming country name is in the first column
            region_name = row[1]  # Assuming region name is in the second column
            
            # Fetch country objects from database
            try:
                country = Country.objects.get(country_name=country_name)
            except ObjectDoesNotExist as e:
                print(f"Error: {e}")
                continue  # Skip this row if institution or bank doesn't exist
            
            # Create dictionary for region data
            region_data = {
                'country_id': country,
                'region_name': region_name
            }
            
            # Append account data to list
            regions_data.append(region_data)

        # Insert data into the model
        for data in regions_data:
            Region.objects.create(**data)
    except FileNotFoundError:
        print("File not found. Please check the path to the Excel file.")
    except Exception as e:
        print(f"An error occurred: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('mashinani', '0005_auto_20240403_1435'),
    ]

    operations = [
        migrations.RunPython(insert_regions)
    ]
