# Generated by Django 5.0.2 on 2024-04-03 11:50

from django.db import migrations
import openpyxl
from django.core.exceptions import ObjectDoesNotExist

def insert_counties(apps, schema_editor):
    County = apps.get_model('mashinani', 'County')
    Region = apps.get_model('mashinani', 'Region')

    try:
        # Load data from Excel workbook
        wb = openpyxl.load_workbook('mashinani/data/data.xlsx')
        sheet = wb['County']

        # Iterate over rows in the Excel sheet and extract region information
        counties_data = []
        for row in sheet.iter_rows(min_row=2, values_only=True):  # Assuming data starts from second row
            region_name = row[0]  # Assuming region name is in the first column
            county_name = row[1]  # Assuming country name is in the second column
            
            # Fetch region objects from database
            try:
                region = Region.objects.get(region_name=region_name)
            except ObjectDoesNotExist as e:
                print(f"Error: {e}")
                continue  # Skip this row if institution or bank doesn't exist
            
            # Create dictionary for region data
            county_data = {
                'region_id': region,
                'county_name': county_name
            }
            
            # Append county data to list
            counties_data.append(county_data)

        # Insert data into the model
        for data in counties_data:
            County.objects.create(**data)
    except FileNotFoundError:
        print("File not found. Please check the path to the Excel file.")
    except Exception as e:
        print(f"An error occurred: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('mashinani', '0006_auto_20240403_1437'),
    ]

    operations = [
        migrations.RunPython(insert_counties)
    ]
