# Generated by Django 5.0.2 on 2024-04-03 12:15

from django.db import migrations
import openpyxl
from django.core.exceptions import ObjectDoesNotExist

def insert_constituencies(apps, schema_editor):
    Constituency = apps.get_model('mashinani', 'Constituency')
    County = apps.get_model('mashinani', 'County')

    try:
        # Load data from Excel workbook
        wb = openpyxl.load_workbook('mashinani/data/data.xlsx')
        sheet = wb['Constituency']

        # Iterate over rows in the Excel sheet and extract constituencies information
        constituencies_data = []
        for row in sheet.iter_rows(min_row=2, values_only=True):  # Assuming data starts from second row
            county_name = row[0]  # Assuming county name is in the first column
            constituency_name = row[1]  # Assuming constituency name is in the second column
            
            # Fetch county objects from database
            try:
                county = County.objects.get(county_name=county_name)
            except ObjectDoesNotExist as e:
                print(f"Error: {e}")
                continue  # Skip this row if institution or bank doesn't exist
            
            # Create dictionary for constituency data
            constituency_data = {
                'county_id': county,
                'constituency_name': constituency_name
            }
            
            # Append constituency data to list
            constituencies_data.append(constituency_data)

        # Insert data into the model
        for data in constituencies_data:
            Constituency.objects.create(**data)
    except FileNotFoundError:
        print("File not found. Please check the path to the Excel file.")
    except Exception as e:
        print(f"An error occurred: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('mashinani', '0007_auto_20240403_1450'),
    ]

    operations = [
        migrations.RunPython(insert_constituencies)
    ]
