# Generated by Django 5.0.2 on 2024-04-03 12:19

from django.db import migrations
import openpyxl
from django.core.exceptions import ObjectDoesNotExist

def insert_wards(apps, schema_editor):
    Ward = apps.get_model('mashinani', 'Ward')
    Constituency = apps.get_model('mashinani', 'Constituency')

    try:
        # Load data from Excel workbook
        wb = openpyxl.load_workbook('mashinani/data/data.xlsx')
        sheet = wb['Ward']

        # Iterate over rows in the Excel sheet and extract ward information
        wards_data = []
        for row in sheet.iter_rows(min_row=2, values_only=True):  # Assuming data starts from second row
            constituency_name = row[0]  # Assuming constituency name is in the first column
            ward_name = row[1]  # Assuming ward name is in the second column
            
            # Fetch constituency objects from database
            try:
                constituency = Constituency.objects.get(constituency_name=constituency_name)
            except ObjectDoesNotExist as e:
                print(f"Error: {e}")
                continue  # Skip this row if institution or bank doesn't exist
            
            # Create dictionary for constituency data
            ward_data = {
                'constituency_id': constituency,
                'ward_name': ward_name
            }
            
            # Append ward data to list
            wards_data.append(ward_data)

        # Insert data into the model
        for data in wards_data:
            Ward.objects.create(**data)
    except FileNotFoundError:
        print("File not found. Please check the path to the Excel file.")
    except Exception as e:
        print(f"An error occurred: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('mashinani', '0008_auto_20240403_1515'),
    ]

    operations = [
        migrations.RunPython(insert_wards)
    ]
