# Generated by Django 5.0.2 on 2024-04-03 13:12

from django.db import migrations
import openpyxl
from django.core.exceptions import ObjectDoesNotExist

def insert_residents(apps, schema_editor):
    Resident = apps.get_model('mashinani', 'Resident')
    Ward = apps.get_model('mashinani', 'Ward')

    try:
        # Load data from Excel workbook
        wb = openpyxl.load_workbook('mashinani/data/data.xlsx')
        sheet = wb['Resident']

        # Iterate over rows in the Excel sheet and extract resident information
        residents_data = []
        for row in sheet.iter_rows(min_row=2, values_only=True):  # Assuming data starts from second row
            national_id_no = row[0]  # Assuming National ID Number is in the first column
            ward_name = row[1]  # Assuming ward name is in the second column
            
            # Fetch residents objects from database
            try:
                ward = Ward.objects.get(ward_name=ward_name)
            except ObjectDoesNotExist as e:
                print(f"Error: {e}")
                continue  # Skip this row if ward  doesn't exist
            
            # Create dictionary for resident data
            resident_data = {
                'national_id_no': national_id_no,
                'ward_id': ward
            }
            
            # Append resident data to list
            residents_data.append(resident_data)

        # Insert data into the model
        for data in residents_data:
            Resident.objects.create(**data)
    except FileNotFoundError:
        print("File not found. Please check the path to the Excel file.")
    except Exception as e:
        print(f"An error occurred: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('mashinani', '0009_auto_20240403_1519'),
    ]

    operations = [
        migrations.RunPython(insert_residents)
    ]
